config/routes.rb
Rails.application.routes.draw do
  
  
  
  resources :courses, only:[:show] do
    resources :exercises, only:[:new, :create, :destroy, :edit, :update]
  end
  
  
  resources :exercises, except:[:show, :index] do
    resources :results
  end
  
  get 'new-course', to:"courses#new"

  resources :courses, except:[:show, :new]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "courses#index"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = current_user.courses.build(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :content, :slug, :user_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
    
    
</div>

app/views/courses/_form.html.erb
<%= form_with(model: course, class: "contents") do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.rich_text_area :content, class: "block rounded-md border border-black bg-white outline-none px-3 py-2 mt-2 w-full" %>
  </div>


  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/courses/_navbar.html.erb
<!-- Page Scroll Progress -->
<div class="fixed inset-x-0 top-0 z-50 h-0.5 mt-0.5 bg-blue-500" :style="`width: ${percent}%`"></div>

<!-- Navbar -->
<nav
    class="flex justify-around py-4 bg-white/80
                                            backdrop-blur-md shadow-md w-full
                                            fixed top-0 left-0 right-0 z-10">
    <!-- Logo Container -->
    <div
        class="flex items-center">
        <!-- Logo -->
        <a class="cursor-pointer">
            <h3 class="text-2xl font-medium text-blue-500">
                <span class="h-10 object-cover">Lnclass</span>
                <%#= image_tag("favicons/favicon-32x32", class:"h-10 object-cover", alt:"Store Logo") %>
            </h3>
        </a>
    </div>

    <!-- Links Section -->
    <div class="items-center hidden space-x-8 lg:flex">
        <%= link_to 'Accueil', root_path, class:"flex text-gray-600 hover:text-blue-500
                                            cursor-pointer transition-colors duration-300" %>

        <%= link_to 'Dashboard',  root_path, class:"flex text-gray-600
                                            cursor-pointer transition-colors duration-300
                                            font-semibold text-blue-600" %>
        <%= link_to 'Corrections',  root_path, class:"flex text-gray-600
                                            cursor-pointer transition-colors duration-300
                                            font-semibold text-blue-600" %>


        <%= link_to 'Abonnement', '#', class:"flex text-gray-600 hover:text-blue-500
                                            cursor-pointer transition-colors duration-300"%>


    </div>

    <!-- Icon Menu Section -->
    <div class="flex items-center space-x-5">
        <%# if user_signed_in? %>

        <!-- Register -->
            <%= link_to "#", class:"flex text-gray-600 hover:text-blue-500
                                            cursor-pointer transition-colors duration-300" do %>

                <svg class="fill-current h-5 w-5 mr-2 mt-0.5" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="24" height="24" viewbox="0 0 24 24"> <path d="M12 0L11.34 .03L15.15 3.84L16.5 2.5C19.75 4.07 22.09 7.24 22.45 11H23.95C23.44 4.84 18.29 0 12 0M12 4C10.07 4 8.5 5.57 8.5 7.5C8.5 9.43 10.07 11 12 11C13.93 11 15.5 9.43 15.5 7.5C15.5 5.57 13.93 4 12 4M12 6C12.83 6 13.5 6.67 13.5 7.5C13.5 8.33 12.83 9 12 9C11.17 9 10.5 8.33 10.5 7.5C10.5 6.67 11.17 6 12 6M.05 13C.56 19.16 5.71 24 12 24L12.66 23.97L8.85 20.16L7.5 21.5C4.25 19.94 1.91 16.76 1.55 13H.05M12 13C8.13 13 5 14.57 5 16.5V18H19V16.5C19 14.57 15.87 13 12 13M12 15C14.11 15 15.61 15.53 16.39 16H7.61C8.39 15.53 9.89 15 12 15Z"/>
            </svg>

            <%= current_user.email %>
        <% end %>
        <%# else %>
        <!-- Login -->
        <%= link_to destroy_user_session_path, method: :delete, class:"flex text-gray-600
                                                cursor-pointer transition-colors duration-300
                                                font-semibold text-blue-600" do %>

            <svg class="fill-current h-5 w-5 mr-2 mt-0.5" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="24" height="24" viewbox="0 0 24 24">
                <path d="M10,17V14H3V10H10V7L15,12L10,17M10,2H19A2,2 0 0,1 21,4V20A2,2 0 0,1 19,22H10A2,2 0 0,1 8,20V18H10V20H19V4H10V6H8V4A2,2 0 0,1 10,2Z"/>
            </svg>
            Se Déconnecter
        <% end %>

        <%# end %>
    </div>
</nav>

app/views/courses/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing course</h1>

  <%= render "form", course: @course %>

  <%= link_to "Show this course", @course, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to courses", courses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/courses/index.html.erb
<% @title="Accueil" %>
<!-- Navbar -->
<%= render "courses/navbar" %>

<div class="w-full mt-20">
    <!-- New Course -->
    <div class="flex justify-between items-center">
        <h1 class="font-bold text-4xl">Courses</h1>
        <%= link_to 'New course', "new-course", class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>

    <!-- Feed Course -->
    <div id="courses" class=" mx-auto md:w-2/3 ">
        <% @courses.each do |course| %>
            <%= turbo_frame_tag :feed_course do %>
                <%= link_to course_path(course) do %>
                    <div class="border m-2 bg-white">
                        <div class="text-xl p-2">
                            <h1 class="font-bold"><%= course.title %></h1>
                        </div>
                        <div class="border m-2 p-2">
                            <%= truncate(strip_tags(course.content.to_s.html_safe), length: 500) %>
                        </div>
                    </div>
                <% end %>
            <% end %>
        <% end %>
    </div>

</div>

app/views/courses/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New course</h1>

  <%= render "form", course: @course %>

  <%= link_to 'Back to courses', courses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/courses/show.html.erb
<%= turbo_frame_tag :feed_course do %>
  <div id="<%= dom_id @course %>" class="mx-auto w-full flex">

    <div class="mx-auto">
      <!-- Show course card-->
    <div class="border m-2">
        <!-- Course detail-->
        <div class="border bg-white m-2 p-2">
          <!-- Course title-->
          <div class="text-xl p-2">
              <h1 class="font-bold"><%= @course.title %></h1>
          </div>
            <%= @course.content %>
        </div>

        <!-- Exercises Feed-->
        <div class="border bg-white m-2">
            <%= render "courses/shared/exercises", course:@course %>
        </div>
    </div>

        <!-- Options-->
      <%= link_to 'Edit this course', edit_course_path(@course), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <div class="inline-block ml-2">
        <%= button_to 'Destroy this course', course_path(@course), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
      <%= turbo_frame_tag :Add_exercise do %>
          <%= link_to 'New Exercise', new_course_exercise_path(@course), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <% end %>

    </div>
  </div>
<% end %>