config/routes.rb
Rails.application.routes.draw do
  
  
  
  resources :courses, only:[:show] do
    resources :exercises, only:[:new, :create, :destroy, :edit, :update]
  end
  
  
  resources :exercises, except:[:show, :index] do
    resources :results
  end
  
  get 'new-course', to:"courses#new"

  resources :courses, except:[:show, :new]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "courses#index"
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course, only: %i[new create]
  before_action :set_exercise, only: %i[ show edit update destroy ]

  # GET /exercises or /exercises.json
  def index
    @exercises = Exercise.all
  end

  # GET /exercises/1 or /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = @course.exercises.build()
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises or /exercises.json
  def create
    @exercise = @course.exercises.build(exercise_params)
    @exercise.user_id = current_user.id

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to course_path(@course), notice: "Exercise was successfully created." }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1 or /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to exercise_url(@exercise), notice: "Exercise was successfully updated." }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1 or /exercises/1.json
  def destroy
    @exercise.destroy

    respond_to do |format|
      format.html { redirect_to exercises_url, notice: "Exercise was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.friendly.find(params[:id])
    end

    def set_course
      @course = Course.friendly.find(params[:course_id])
    end

    # Only allow a list of trusted parameters through.
    def exercise_params
      params.require(:exercise).permit(:title, :content, :correction, :slug, :user_id, :course_id,  
        questions_attributes:[:_destroy,:id, :question_type, :name, 
          answers_attributes: [:_destroy, :id, :name]])
    end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_answer_fields.html.erb
<div class='nested-fields'>
    <div class='form-group flex'>
        <%= form.hidden_field :_destroy %>
        <div class="flex">
            <div class="">
                <%= form.radio_button :correct, checked_value: true, unchecked_value: false  %>
                <%= form.text_field :name, placeholder: 'Réponse ...', class: '' %>
            </div>
        </div>
    </div>
    <div class="">
        <small>
            <%= link_to "Supprimé", "#", data: { action: "click->nested-form#remove_association" },
          class:"Add-item-delete" %>
        </small>
    </div>
</div>

app/views/exercises/_exercise.html.erb
<div id="<%= dom_id exercise %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= exercise.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Content:</strong>
    <%= exercise.content %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Correction:</strong>
    <%= exercise.correction %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Slug:</strong>
    <%= exercise.slug %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= exercise.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Course:</strong>
    <%= exercise.course_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this exercise", exercise, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this exercise', edit_exercise_path(exercise), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/exercises/_form.html.erb
<%= form_with(model: exercise, url: [@course, exercise], class: "contents") do |form| %>
  <% if exercise.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
        <% exercise.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.rich_text_area :content, class: "block bg-white rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :correction %>
    <%= form.rich_text_area :correction, class: "block bg-white rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

<div data-controller="nested-form" data-nested-form-index-value='QUESTION_RECORD' class="my-5  border py-4">
    <template data-nested-form-target='template'>
        <%= form.fields_for :questions, Question.new, child_index: 'QUESTION_RECORD' do |question| %>
            <%= render 'question_fields', form: question %>
        <% end %>
    </template>

      <%= form.fields_for :questions do |question| %>
        <%= render 'question_fields', form: question %>
      <% end %>

        <!-- Add Question button-->
            <div data-nested-form-target="add_item"> <%= link_to "Question", "#", data: { action: "nested-form#add_association" },
        class:"Add-item-exercise" %>
        </div>
    </div>




  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/exercises/_question_fields.html.erb
<div class='nested-fields box px-2' data-controller='dynamic-select'>
    <div class='form-group mb-2'>
        <%= form.select :question_type,
        options_for_select(Question.question_type_select, selected: form.object.question_type),
        {},
        'data-dynamic-select-target': 'select',
        'data-action': 'dynamic-select#selected' %>
    </div>

    <div class='form-group '>
        <%= form.hidden_field :_destroy %>
        <%= form.text_field :name, placeholder: 'Nouvelle Question', class:'w-full ' %>
        <small>
            <%= link_to "Supprimé", "#", data: { action: "click->nested-form#remove_association" },
      class:"add-item-delete" %>
        </small>
    </div>

    <div data-controller="nested-form" data-nested-form-index-value='ANSWER_RECORD' data-dynamic-select-target='choice'>
        <template data-nested-form-target='template'>
            <%= form.fields_for :answers, Answer.new, child_index: 'ANSWER_RECORD' do |answer| %>
                <%= render 'answer_fields', form: answer %>
            <% end %>
        </template>

        <%= form.fields_for :answers do |answer| %>
            <%= render 'answer_fields', form: answer %>
        <% end %>

        <div data-nested-form-target="add_item" class=" my-4">
            <%= link_to "Réponse", "#", data: { action: "nested-form#add_association" },
        class:"Add-item-exercise" %>
        </div>
    </div>

    <div data-controller="nested-form" data-dynamic-select-target='long'></div>
</div>

app/views/exercises/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing exercise</h1>

  <%= render "form", exercise: @exercise %>

  <%= link_to "Show this exercise", @exercise, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to exercises", exercises_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/exercises/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Exercises</h1>
    <%= link_to 'New exercise', new_exercise_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="exercises" class="min-w-full">
    <%= render @exercises %>
  </div>
</div>

app/views/exercises/new.html.erb
<%= turbo_frame_tag :Add_exercise  do %>
<div class="mx-auto bg-white p-2 w-full">
  <h1 class="font-bold text-4xl">New exercise</h1>
  <%= render "form", exercise: @exercise %>
  <%#= link_to 'Back to exercises', exercises_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

<% end %>

app/views/exercises/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @exercise %>

    <%= link_to 'Edit this exercise', edit_exercise_path(@exercise), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this exercise', exercise_path(@exercise), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to exercises', exercises_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>